### ISSUE TITLE
Error log :when i played with 2 players TNH mode,after 2 holds it shows,then we desync enemies and gunshot sound.

### ISSUE THREAD

**Issue by Vocalnoid** [TommySoucy/H3MP#101]
![OSV0RZJ1AEZ(59U3G 73`F2](https://github.com/TommySoucy/H3MP/assets/135813682/ffe8bca3-0dc4-4ebb-8418-70243d8cb47b)

**Comment by TommySoucy** [comment]
Was that with all players using H3MP 1.6.3?

Also give me the full logs you can get from R2, settings > Copy log file content to clipboard, paste it here

**Comment by TommySoucy** [comment]
Also who was the server and who was the TNH instance host? And whos console is that? Was it the server taht was getting these errors?

**Comment by Vocalnoid** [comment]
> Also who was the server and who was the TNH instance host? And whos console is that? Was it the server that was getting these errors?
Sorry I didn't notice that you updated to a new version, it seems to fix the "out of range" bug. I'll find time to test it again with a friend. Thanks for your dedication!
