### ISSUE TITLE
Muzzle Loading Guns, and gun animations not having there states synchronized or animations playing while in use by other players.

### ISSUE THREAD

**Issue by Nattie98** [TommySoucy/H3MP#106]
Any muzzle loading gun used by other players will not have its status synchronize with the client. And animation on some guns like Hand crank Frank wont play out or be seen by the client when used by other people.

**Comment by TommySoucy** [comment]
What do you mean by muzzle loading gun not having their status synced? Firearm doesn't fire? Chamber doesn't get loaded? Which firearms exactly so I can test?

Animations and visual aspects were discussed before. Not only would implementing synchronizing animations like that take up more bandwidth in the network, but it would also require me to go through every single item in the game to manually implement their specific animations. It won't happen unless it becomes particularly important for a specific item's animations to be synced.

**Comment by TommySoucy** [comment]
There were some known early issues with firearms like the musket. I'll be looking at that again eventually.
