### ISSUE TITLE
Far off sounds created by other players not being heard.

### ISSUE THREAD

**Issue by Nattie98** [TommySoucy/H3MP#107]
Any time another player fires a gun and shoots a far off metal target for example the sound of the target is not heard by anyone else but the player who shot the target.

**Comment by TommySoucy** [comment]
See #15 description, will have to review

**Comment by TommySoucy** [comment]
Gotta add support for:

- StaticSteelTarget
- ReactiveSteelTarget
- SteelPopTarget
