### ISSUE TITLE
TNH Desync

### ISSUE THREAD

**Issue by TommySoucy** [TommySoucy/H3MP#119]
"I tried playing TNH with a friend a few days ago using H3MP, but it quickly broke down and we couldn't continue.
Initially, it all worked fine, we met up, cleared a supply point, and finished the first hold. It was around then that something strange started happening. He was the one hosting, and didn't experience any of these issues.
When I reached the supply point after the first hold, and took out a couple sosigs, they all simply... Fell over? Visually they seemed to be in a state of ducking (Double down orange arrows), but also lying on the floor like they were dead with no visible bullet wounds, or deteriorated shape. It was also at this point that we noticed some weirdness with our avatars.
While the guns we had in our quickbelt slots followed our position just fine, the avatars fell behind, snapping to our current position at an interval. That wasn't the huge issue though, the real problem happened when we went to the second hold.
When we got there, and killed the guards, I went and started the hold, which started off fine (Supposedly, as I never got a chance to see the sosigs approaching), when my friend pointed out that it hadn't started on his end, so he went to start it himself, which it did for him. I however had my hold interrupted, and set back to the state before I touched the sphere. While the hold was going for him, I saw sosigs approaching, but SEVERELY BROKEN.
They didn't move normally, and instead stood in place for an extended period of time. What REALLY confused me though was the fact that they had random parts of their bodies missing. One of them was just a torso. No matter how many times I shot at them, they never broke. After the hold finished on their end, we decided it wasn't worth continuing, and stopped playing.

I want to know how this all could have happened. After thinking about it for a while, the only conclusion I can come up with is that we may have been on different branches of the game, and thus maybe some code or assets were missing, casing a severe desync. If not that, then what else could it have been? H3MP and BepinEx were the only mods being used by both of us."

**Comment by TommySoucy** [comment]
There first is this error on client side:

```
[Error  :      H3MP] Client TCP received packet with ID: 1179648 as ServerPackets: 1179648:
  at H3MP.Networking.Client+TCP+<>c__DisplayClass8_0.<HandleData>b__0 () [0x00000] in <filename unknown>:0 
```

At this point, the server had sent destruction for 3 tracked objects. These destruction orders were never received. Presumably, the destruction orders where a part of the data that was received here that gave the error. Note that the error says that the packet ID was 1179648, which obviously doesn't have an entry in the enum. 

The data was either processed incorrectly upon receiving it, or sent incorrectly. The prior being more plausible as further in the logs we get update errors that read:

```
[Error  :      H3MP] Client got update for object at 1098732698 which is out of range of objects array
[Error  :      H3MP] Client got update for object at 181403843 which is out of range of objects array
[Error  :      H3MP] Client got update for object at 16252 which is out of range of objects array
[Error  : Unity Log] Exception: Could not read value of type 'ushort'!
Stack trace:
H3MP.Networking.Packet.ReadUShort (Boolean _moveReadPos)
H3MP.Tracking.TrackedObjectData.Update (H3MP.Networking.Packet packet, Boolean includesLength, Boolean full)
H3MP.Networking.ClientHandle.TrackedObjects (H3MP.Networking.Packet packet)
H3MP.Networking.Client+UDP+<>c__DisplayClass6_0.<HandleData>b__0 ()
H3MP.Networking.ThreadManager.UpdateMain ()
H3MP.Networking.ThreadManager.Update ()
```

Note that this error is repeated multiple times with different numbers. But the first number seems to be incrementing on each error by avg.: 1700. This is a few hundred bytes above our hard limit for the size of update packets. What we could be reading as the first number in these errors could be the size of the packet(?) incrementing every time we receive an update. We could look into a buffer possibly not being cleared properly or something. The idea is that something happens when we read received data, which causes a fault that never gets cleared and ends up propagating down the line into constant error and resulting desync. This probably happens more in TNH simply because there is a lot more happening.

Note that this same error happens again later but this time with the first number being a constant 147.

**Comment by TommySoucy** [comment]
All TNH testing done by myself was done with another system hosting or being connected but not playing. all scenarios were tested: Them as Server/Client, hosting TNH, not hosting TNH, initializing/not initializing, etc. Everything worked without any desync. I played through 3 holds and 5 holds without any trouble at all.

This points to desync being caused by another player having to instantiate/destroy/interact with items.

If this other system initializes the game, they spawn their initial equipment as in vanilla.
These items get registered to the TNH_Manager or supply point to get destroyed when hold starts or supply point gets activated, respectively.
They never interact with these items because they just sit there all game.

I will be switching ObjectCleanupInHoldTranspiler over to a prefix for readability and reviewing the necessity for AddFVRObjectToTrackedListPrefix in TNHPatches.

I will probably be adding debug functionality to be able to control a player that is using the null driver, in order to test item interaction.

**Comment by TommySoucy** [comment]
Also of note is that during desync, objects are clearly being IDed wrong.

By this I mean that an object somehow takes the ID of another object. This results in some player's item(s) being replaced with another. In TNH this is clearly visible when it happens as a player's firearm turning into a TNH crate or a sosig.

This kind of desync could only happen in specific places in the code. Somehow, objects are getting another's ID. Two clients track different objects using the same trackedID.

**Comment by TommySoucy** [comment]
May be related:

When destroying an object with physical tracked children, obviously, destruction will also be called for those children.

So when we have a firearm with attachments and a client destroys it, they will send destruction of the item and all of its children.
Then another client receives the order to destroy the parent child, and if they have the physical of it, it will be destroyed and then will destroy the children. We do not resend the destruction of the parent object, but we will send the destruction of the children.

This must be prevented. Consider the scenario in which such an item is destroyed, then right away, the destroying client instantiates a new object using on the the IDs that were just freed by the destruction. Another client receives order to destroy on their side, destroy their item, and then sends a new destruction order for the children. The original client receives the destruction for the children, for which the ID has now been reused. They will proceed with the destruction of the item at that ID, and the order to destroy the new item at that ID will never be sent out. The result is tracked ID desync. 

This may be the case in TNH when we start a hold, destroying items outside of the hold area, instantiating new ones like Sosigs. This could be causing the TNH desync.

**Comment by TommySoucy** [comment]
A fix for this would be to prevent sending destruction of children as well if destruction was ordered by another client

**Comment by TommySoucy** [comment]
Consider scenario:
Client sends object destruction and subsequent destruction of children
Server receives destruction of parent object, destroys it and its children
Server instantiates new objects, taking the deallocated IDs from the parent object and its children
Server receives destruction of children objects at IDs that are now allocated to new objects and destroys them

This leads to more ID desync

Preventing the immediate reuse of tracked IDs would prevent this, within limits. We could make the available IDs into a queue, so that newly deallocated IDs get readded to the end of the queue and will only be reused after other available IDs. If, for example, the queue only has a single element though, this ID can be the first and last and the desync could still happen. This could be further prevented by increasing the objects array size when available number of IDs reaches a higher numbers instead of 0. The current increase in size is 100 elements at a time when available IDs' size == 0. We could instead increase it at 50. This would give a buffer of 50 IDs that would need to be used at any time before reusing newly deallocated IDs. This could still result in desync but only in the case that we deallocate an ID and then allocate 51 of them to new objects, reusing the last one we deallocated.

**Comment by TommySoucy** [comment]
Essentially the problem comes from the server reallocating an ID that was still active in another client. If that other client send orders relating to that ID, we have desync. We must prevent the server from reallocating the ID until we are sure it is no longer active in another client. 

To do this, instead of readding an ID directly in the available tracked ID list, we can add them to a temporary list. The server would then send a signal to all clients to get rid of this ID and request confirmation. Only once it has received confirmation by all clients that were active at the time, will it readd the ID to the available list. Note that in the case that a client destroys a parent and its children, server receives parent destruction and destroys children on its own side, it would only be necessary to request confirmation from the sending client and only about the children of the parent object. This is because the client will have already confirmed getting rid of the parent ID (having destroyed it) and other clients will receive destruction order of the objects from the server itself, unconditionally getting rid of the IDs on their side. So some optimization is possible. Further, we could limit the request of such confirmation to only 1 at a time (only requesting another when we got full confirmation of the first) to prevent flooding the network in the case that many objects were destroyed at once.

**Comment by TommySoucy** [comment]
Considering how complex the buffer system is, and that it is really just a verification mechanism to make sure we don't reuse the same ID, it might not be the best option. 

We can look at the problem from the client's perspective instead: A client receives full object data from the server only in certain cases. Currently, if we already have data at the ID, we assume it is the same object. This is wrong. Obviously, as described by the problem, the server can have an ID for an object while a client can have the same ID for a different object. A solution would be a way to identify whether the object is the actually the same despite the tracked ID. In certain cases though we may be able to omit this check and simply replace the data with the new one no matter what.

**Comment by TommySoucy** [comment]
Desync was reported in 1.6.7

**Comment by TommySoucy** [comment]
Current leads:

- Possibly a TNH unique process with destruction of items outside hold room when hold starts. Review that entire process.
- Possibly caused by Sosigs, considering Sosigs in grillhouse are apparently broken as well and TNH and grillhouse are really the only scenes/gamemodes we support that have Sosigs in them.

**Comment by TommySoucy** [comment]
Latest desync output for 1.7.1 indicate that the server TNH instance host, at the start of take phase, spawning multiple sosigguns and sosigs, adding them locally and assigning them the first IDs above 300, did not send their data to the single client that was in the TNH game with them. Debug output to track down whether the data is being sent and not received has been added for next release.

**Comment by TommySoucy** [comment]
Before we fixed them two transpilers relevant to TNH were not being aplpied:
```
[Error  :      H3MP] SosigActionPatch SpeechUpdateTranspiler not applied!
[Error  :      H3MP] EncryptionPatch UpdateTranspiler not applied!
```
Perhaps reason why we never got desync in testing was not because we never had 2 players interacting at the same time but instead because these patches were being applied on other people's games but not ours. Investigate that possibility.

**Comment by TommySoucy** [comment]
Server TNH instance host, 1 client, only client kills Sosigs: No desync, no error on first run, but 1 invisible Sosig to client, isolated case, he could see others after, and SosigGuns did no damage to client, even when shot by host.

**Comment by TommySoucy** [comment]
One cause of what people have been calling "desync" was really just the game breaking because H3MP failed to track AutoMeaters properly. This would only be caused by characters that spawn the turrets, so never showed up in testing. Will have to see if this "desync" still happens on next release with AutoMeater tracking fixed

**Comment by KernfusionGit** [comment]
Hey Tommy, 

Me and my friend often have desync issues. 
My friend is always hosting, we had nights where everything went fine and on other occasions its desyncing every 5 min. The Debug hold host start don't seem to work for us either.

Here is my logfile, i hope you can see something in there.
https://pastebin.com/syJyCbS6

My buddy can provide you his file as well if needed

But when it works its a great mod! Keep up the good work :)
Laters

**Comment by TommySoucy** [comment]
I would need your friend's output as well, yes

**Comment by DerDegenhardt** [comment]
[LogOutput.log](https://github.com/TommySoucy/H3MP/files/12489822/LogOutput.log)
There it is.

**Comment by TommySoucy** [comment]
Perfect, thank you, I'll take a look

**Comment by TommySoucy** [comment]
Issue:
TCP data buffer had limit of 4096 bytes.
If we receive more than that, it is possible that the last few bytes of data are the start of a new packet, before it gets cut off and the rest of its data ends up in the buffer in the next callback.
For some reason, if those few bytes were > 0 && < 4 bytes, we would discard them.
Making us assume that the start of the rest of the data was the actual start of the packet, creating corrupted packets, breaking the entire TCP process.
