### ISSUE TITLE
error host

### ISSUE THREAD

**Issue by PENPINAPPLEAPPLECAT** [TommySoucy/H3MP#129]
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object                       Stack trace:                                                                                                            H3MP.WristMenuSection.OnHostClicked (UnityEngine.UI.Text) <0x00141>                                                     H3MP.WristMenuSection/<>c__DisplayClass13_0.<InitButton>b__0 () <0x00020>                                               UnityEngine.Events.InvokableCall.Invoke (object[]) <0x00039>                                                            UnityEngine.Events.InvokableCallList.Invoke (object[]) <0x000c4>                                                        UnityEngine.Events.UnityEventBase.Invoke (object[]) <0x00043>                                                           UnityEngine.Events.UnityEvent.Invoke () <0x00023>                                                                       FistVR.FVRPointableButton.OnPoint (FistVR.FVRViveHand) <0x00091>                                                        FistVR.FVRViveHand.set_CurrentPointable (FistVR.FVRPointable) <0x00075>                                                 (wrapper dynamic-method) FistVR.FVRViveHand.DMD<FistVR.FVRViveHand..Update> (FistVR.FVRViveHand) <0x00d87>              (wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<FistVR.FVRViveHand..Update>?2116597760 (FistVR.FVRViveHand) <0x0001c>                                                                                                 BetterHands.MagPalming.MagPalmInput.FVRViveHand_Update (On.FistVR.FVRViveHand/orig_Update,FistVR.FVRViveHand) <0x00074> (wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<FistVR.FVRViveHand..Update>?1328934400 (FistVR.FVRViveHand) <0x0005f>

**Comment by DMJester** [comment]
Me and 2 of my friends had the same problem. 
I was able to play normally after restoring to 1.6.5

**Comment by TommySoucy** [comment]
Were you and your friends on alpha - mod safe?

Also i need full logs

**Comment by DMJester** [comment]
In version 1.6.5, it was possible to play normally.

I looked in the log file, but it seems that the part where the error was was deleted.

However, if I remember correctly, it seems to be the same as the log written above.

**Comment by TommySoucy** [comment]
Can you send full logs?

**Comment by DMJester** [comment]
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
H3MP.WristMenuSection.OnHostClicked (UnityEngine.UI.Text textRef)
H3MP.WristMenuSection+<>c__DisplayClass13_0.<InitButton>b__0 ()
UnityEngine.Events.InvokableCall.Invoke (System.Object[] args)
UnityEngine.Events.InvokableCallList.Invoke (System.Object[] parameters)
UnityEngine.Events.UnityEventBase.Invoke (System.Object[] parameters)
UnityEngine.Events.UnityEvent.Invoke ()
FistVR.FVRPointableButton.OnPoint (FistVR.FVRViveHand hand)
FistVR.FVRViveHand.set_CurrentPointable (FistVR.FVRPointable value)
FistVR.FVRViveHand.Update ()

[Info   :      H3MP] Closing server.
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
H3MP.GameManager.TakeAllPhysicalControl (Boolean destroyTrackedScript)
H3MP.Networking.Server.Close ()
H3MP.Networking.ThreadManager.OnApplicationQuit ()

[Info   : Unity Log] LIV: Disabled, cleaning up.

------------------------------------------

This is the log part that appears when you update to version 1.6.7 and click the Host button in the H3MP menu.

Playable in 1.6.5 with the same mod list

---------- full log down to this ----------

[Message:   BepInEx] BepInEx 5.4.17.0 - h3vr (3/22/2023 6:59:32 AM)
[Info   :   BepInEx] Running under Unity v5.6.7.15207619
[Info   :   BepInEx] CLR runtime version: 2.0.50727.1433
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.17.0]
[Info   :   BepInEx] Loaded 1 patcher method from [Deli.Patcher 0.4.2.0]
[Info   :   BepInEx] Loaded 1 patcher method from [H3VR.Sideloader.MonoMod 0.3.6.0]
[Info   :   BepInEx] Loaded 1 patcher method from [Sodalite.Patcher 1.0.0.0]
[Info   :   BepInEx] Loaded 1 patcher method from [Deliter 1.0.0.0]
[Info   :   BepInEx] Loaded 1 patcher method from [Mason.Patcher 1.0.0.0]
[Info   :   BepInEx] 6 patcher plugins loaded
[Info   :      Deli] Deli bootstrap has begun! Version 0.4.2 (main @ 4952ff9)
[Info   :   BepInEx] Patching [UnityEngine] with [BepInEx.Chainloader]
[Info   :      Deli] Found 9 mods to load
[Message:      Deli] Patcher stage started
[Info   :      Deli] Loading [Deli 0.4.2] modules into patcher
[Info   :      Deli] Loading patcher assets from [MagazinePatcher 0.1.12]
[Message:      Deli] Patcher stage finished
[Info   :   BepInEx] Patching [Assembly-CSharp] with [H3VR.Sideloader.MonoMod.SideloaderMonoModPatcher]
[Message:Sideloader.MonoMod] Scanning mods
[Message:Sideloader.MonoMod] Found 0 mods
[Info   :Mason Patcher] Bootstrapping Mason
[Info   :Mason Patcher] Found 23 possible projects
[Info   :Mason Patcher] Compiled abass20-BlackHawkDownTNH-1.0.0 with 0 warnings
[Warning:Mason Patcher] 
warning at C:\Users\xment\AppData\Roaming\r2modmanPlus-local\H3VR\profiles\H3MP_Only\BepInEx\plugins\devyndamonster-IslandCompound\manifest.json(0,0): [C10] The author of the mod was infered by the directory name. Consider adding an 'author' property.
[Info   :Mason Patcher] Compiled devyndamonster-IslandCompound-1.5.5 with 1 warnings
[Warning:Mason Patcher] 
warning at C:\Users\xment\AppData\Roaming\r2modmanPlus-local\H3VR\profiles\H3MP_Only\BepInEx\plugins\devyndamonster-OtherLoader\manifest.json(0,0): [C10] The author of the mod was infered by the directory name. Consider adding an 'author' property.
[Info   :Mason Patcher] Compiled devyndamonster-OtherLoader-1.3.7 with 1 warnings
[Warning:Mason Patcher] 
warning at C:\Users\xment\AppData\Roaming\r2modmanPlus-local\H3VR\profiles\H3MP_Only\BepInEx\plugins\Nikpo-Rostok_TnH\manifest.json(0,0): [C10] The author of the mod was infered by the directory name. Consider adding an 'author' property.
[Info   :Mason Patcher] Compiled Nikpo-Rostok_TnH-1.0.2 with 1 warnings
[Warning:Mason Patcher] 
warning at C:\Users\xment\AppData\Roaming\r2modmanPlus-local\H3VR\profiles\H3MP_Only\BepInEx\plugins\sirpotatos-AltMags\manifest.json(0,0): [C10] The author of the mod was infered by the directory name. Consider adding an 'author' property.
[Info   :Mason Patcher] Compiled sirpotatos-AltMags-1.2.0 with 1 warnings
[Warning:Mason Patcher] 
warning at C:\Users\xment\AppData\Roaming\r2modmanPlus-local\H3VR\profiles\H3MP_Only\BepInEx\plugins\sirpotatos-Hotel_Hotlink\manifest.json(0,0): [C10] The author of the mod was infered by the directory name. Consider adding an 'author' property.
[Info   :Mason Patcher] Compiled sirpotatos-Hotel_Hotlink-1.2.2 with 1 warnings
[Message:Mason Patcher] Compilation complete
[Message:   BepInEx] Preloader finished
[Warning:  HarmonyX] AccessTools.Property: Could not find property for type UnityEngine.Application and name isBatchMode
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 16 plugins to load
[Warning:   BepInEx] Plugin [H3MP 1.6.7] targets a wrong version of BepInEx (5.4.21.0) and might not work until you update
[Info   :   BepInEx] Loading [Stratum 1.1.1]
[Info   :   BepInEx] Loading [BlackHawkDownTNH 1.0.0]
[Info   :   BepInEx] Loading [Wristimate 1.1.0]
[Info   :   BepInEx] Loading [Deli 0.4.1]
[Message:      Deli] Setup stage started
[Info   :      Deli] Loading [Deli 0.4.2] modules into setup
[Info   :      Deli] Loading setup assets from [WurstMod 2.2.4]
[Info   :      Deli] Loading setup assets from [BlackHawkDownTNH 1.0.0]
[Info   :  WurstMod] Discovered level BlackHawkDownTNH in [BlackHawkDownTNH 1.0.0], /BlackHawkDownTNH/
[Info   :      Deli] Loading setup assets from [Island Compound 1.5.2]
[Info   :  WurstMod] Discovered level Island Compound in [Island Compound 1.5.2], /IslandCompound/
[Info   :      Deli] Loading setup assets from [MagazinePatcher 0.1.12]
[Info   :      Deli] Loading setup assets from [Freehold 2 TNH Boogaloo 1.2.0]
[Info   :  WurstMod] Discovered level Freehold Rework in [Freehold 2 TNH Boogaloo 1.2.0], /Freehold_rework/
[Info   :      Deli] Loading setup assets from [Wurst City Reloaded Day 1.0.0]
[Info   :  WurstMod] Discovered level Wurst_City Reloaded Day in [Wurst City Reloaded Day 1.0.0], /this_is_the_day_wurst_city/
[Info   :      Deli] Loading setup assets from [Take and Hold - Rostok Bar 0.1.0]
[Info   :  WurstMod] Discovered level Rostok in [Take and Hold - Rostok Bar 0.1.0], /TnH_Rostok/
[Info   :      Deli] Loading setup assets from [Hotel Hotlink 1.2.2]
[Info   :  WurstMod] Discovered level Hotel Hotlink in [Hotel Hotlink 1.2.2], /HotelHotlink/
[Message:      Deli] Setup stage finished
[Message:      Deli] Runtime stage started
[Info   :      Deli] Loading [Deli 0.4.2] modules into runtime
[Info   :   BepInEx] Loading [IslandCompound 1.5.5]
[Info   :   BepInEx] Loading [Sodalite 1.4.2]
[Message:  Sodalite] Game build ID: 11008852 (main).
[Info   :   BepInEx] Loading [OtherLoader 1.3.7]
[Info   : Unity Log] Rewards.txt exists, initializing from it
[Info   :   BepInEx] Loading [OtherLoader 1.3.7]
[Info   :   BepInEx] Loading [XUnity Resource Redirector 1.2.0]
[Info   :   BepInEx] Loading [Player Footsteps 1.0.0]
[Info   :Player Footsteps] Player Footsteps mod loaded
[Info   :   BepInEx] Loading [H3VR Sideloader 0.3.6]
[Warning:  HarmonyX] AccessTools.Method: Could not find method for type UnityEngine.AssetBundle and name LoadFromFileAsync_Internal and parameters (string, uint, ulong)
[Warning:  HarmonyX] AccessTools.Method: Could not find method for type UnityEngine.AssetBundle and name LoadFromFile_Internal and parameters (string, uint, ulong)
[Warning:  HarmonyX] AccessTools.Method: Could not find method for type UnityEngine.AssetBundle and name LoadFromMemoryAsync_Internal and parameters (byte[], uint)
[Warning:  HarmonyX] AccessTools.Method: Could not find method for type UnityEngine.AssetBundle and name LoadFromMemory_Internal and parameters (byte[], uint)
[Warning:  HarmonyX] AccessTools.Method: Could not find method for type UnityEngine.AssetBundle and name LoadFromStreamAsyncInternal and parameters (System.IO.Stream, uint, uint)
[Warning:  HarmonyX] AccessTools.Method: Could not find method for type UnityEngine.AssetBundle and name LoadFromStreamAsync and parameters (System.IO.Stream, uint, uint)
[Warning:XUnity.Common] Could not hook 'AssetBundle_LoadFromStreamAsync_Hook'. Likely due differences between different versions of the engine or text framework.
[Warning:  HarmonyX] AccessTools.Method: Could not find method for type UnityEngine.AssetBundle and name LoadFromStreamInternal and parameters (System.IO.Stream, uint, uint)
[Warning:  HarmonyX] AccessTools.Method: Could not find method for type UnityEngine.AssetBundle and name LoadFromStream and parameters (System.IO.Stream, uint, uint)
[Warning:XUnity.Common] Could not hook 'AssetBundle_LoadFromStream_Hook'. Likely due differences between different versions of the engine or text framework.
[Warning:  HarmonyX] AccessTools.Method: Could not find method for type UnityEngine.AssetBundle and name returnMainAsset and parameters (UnityEngine.AssetBundle)
[Warning:  HarmonyX] AccessTools.Method: Could not find method for type UnityEngine.AssetBundle and name returnMainAsset and parameters (UnityEngine.AssetBundle)
[Warning:  HarmonyX] AccessTools.Method: Could not find method for type UnityEngine.Resources and name GetBuiltinResource and parameters (string, Type)
[Warning:  HarmonyX] AccessTools.Method: Could not find method for type UnityEngine.AssetBundleCreateRequest and name SetEnableCompatibilityChecks and parameters (bool)
[Warning:  HarmonyX] AccessTools.Method: Could not find method for type UnityEngine.AssetBundleCreateRequest and name SetEnableCompatibilityChecks and parameters (bool)
[Info   :H3VR Sideloader] Loading mods...
[Info   :H3VR Sideloader] Loaded 1 mods!
[Info   :   BepInEx] Loading [TNH_Quality_of_Life_Improvements 1.2.3]
[Info   :   BepInEx] Loading [Rostok_TnH 1.0.2]
[Info   :   BepInEx] Loading [AltMags 1.2.0]
[Info   :   BepInEx] Loading [Hotel_Hotlink 1.2.2]
[Info   :   BepInEx] Loading [H3MP 1.6.7]
[Message:   BepInEx] Chainloader startup complete
[Info   :OtherLoader] Plugins folder found (C:\Users\xment\AppData\Roaming\r2modmanPlus-local\H3VR\profiles\H3MP_Only\BepInEx\plugins)
[Info   :OtherLoader] Legacy folder found (G:/Steam/steamapps/common/H3VR/LegacyVirtualObjects)
[Info   : Unity Log] <b>[SteamVR]</b> Successfully loaded 21 actions from action manifest into SteamVR (G:/Steam/steamapps/common/H3VR/actions.json)
[Info   : Unity Log] <b>[SteamVR]</b> Initialized. Connected to oculus:1WMHH834851165
[Info   : Unity Log] OmniScores.txt exists, initializing from it
[Info   : Unity Log] OmniUnlocks.txt does not exist, creating it
[Info   : Unity Log] OmniScores.txt exists, initializing from it
[Info   : Unity Log] Rewards.txt exists, initializing from it
[Info   : Unity Log] WW.txt exists, initializing from it
[Info   : Unity Log] TAH.txt exists, initializing from it
[Info   : Unity Log] TNH_v2.txt exists, initializing from it
[Info   : Unity Log] MMF.txt exists, initializing from it
[Info   : Unity Log] MF.txt exists, initializing from it
[Info   : Unity Log] ROTRWv2.txt exists, initializing from it
[Info   : Unity Log] Initializing Scene
[Info   : Unity Log] Detected System: oculus quest2 a53ft
[Info   :TNH_Quality_of_Life_Improvements] We are NOT in a TNH game!
[Info   : Unity Log] Initializing level populator...
[Info   :      H3MP] H3MP Started
[Info   :      H3MP] H3MP Init called
[Info   :      H3MP] H3MP path found: C:\Users\xment\AppData\Roaming\r2modmanPlus-local\H3VR\profiles\H3MP_Only\BepInEx\plugins\VIP-H3MP
[Warning:  HarmonyX] AccessTools.Field: Could not find field for type FistVR.FVRFireArmChamber and name SuppressCaselessDeletion
[Error  :  HarmonyX] Failed to patch FistVR.FVRFireArmRound FistVR.FVRFireArmChamber::EjectRound(UnityEngine.Vector3 EjectionPosition, UnityEngine.Vector3 EjectionVelocity, UnityEngine.Vector3 EjectionAngularVelocity, bool ForceCaseLessEject): System.ArgumentException: No such field defined in class FistVR.FVRFireArmChamber
Parameter name: SuppressCaselessDeletion
  at HarmonyLib.Public.Patching.HarmonyManipulator.EmitCallParameter (HarmonyLib.Internal.Util.ILEmitter il, System.Reflection.MethodBase original, System.Reflection.MethodInfo patch, System.Collections.Generic.Dictionary`2 variables, Boolean allowFirsParamPassthrough, Mono.Cecil.Cil.VariableDefinition& tmpObjectVar, System.Collections.Generic.List`1& tmpBoxVars) [0x00000] in <filename unknown>:0 
  at HarmonyLib.Public.Patching.HarmonyManipulator.WritePrefixes (HarmonyLib.Internal.Util.ILEmitter il, System.Reflection.MethodBase original, HarmonyLib.Internal.Util.Label returnLabel, System.Collections.Generic.Dictionary`2 variables, ICollection`1 prefixes, Boolean debug) [0x00000] in <filename unknown>:0 
  at HarmonyLib.Public.Patching.HarmonyManipulator.MakePatched (System.Reflection.MethodBase original, MonoMod.Cil.ILContext ctx, System.Collections.Generic.List`1 prefixes, System.Collections.Generic.List`1 postfixes, System.Collections.Generic.List`1 transpilers, System.Collections.Generic.List`1 finalizers, System.Collections.Generic.List`1 ilmanipulators, Boolean debug) [0x00000] in <filename unknown>:0 
[Error  : Unity Log] ArgumentException: No such field defined in class FistVR.FVRFireArmChamber
Parameter name: SuppressCaselessDeletion
Stack trace:
HarmonyLib.Public.Patching.HarmonyManipulator.EmitCallParameter (HarmonyLib.Internal.Util.ILEmitter il, System.Reflection.MethodBase original, System.Reflection.MethodInfo patch, System.Collections.Generic.Dictionary`2 variables, Boolean allowFirsParamPassthrough, Mono.Cecil.Cil.VariableDefinition& tmpObjectVar, System.Collections.Generic.List`1& tmpBoxVars)
HarmonyLib.Public.Patching.HarmonyManipulator.WritePrefixes (HarmonyLib.Internal.Util.ILEmitter il, System.Reflection.MethodBase original, HarmonyLib.Internal.Util.Label returnLabel, System.Collections.Generic.Dictionary`2 variables, ICollection`1 prefixes, Boolean debug)
HarmonyLib.Public.Patching.HarmonyManipulator.MakePatched (System.Reflection.MethodBase original, MonoMod.Cil.ILContext ctx, System.Collections.Generic.List`1 prefixes, System.Collections.Generic.List`1 postfixes, System.Collections.Generic.List`1 transpilers, System.Collections.Generic.List`1 finalizers, System.Collections.Generic.List`1 ilmanipulators, Boolean debug)
Rethrow as HarmonyException: IL Compile Error (unknown location)
HarmonyLib.Public.Patching.HarmonyManipulator.MakePatched (System.Reflection.MethodBase,MonoMod.Cil.ILContext,System.Collections.Generic.List`1<HarmonyLib.Public.Patching.HarmonyManipulator/PatchContext>,System.Collections.Generic.List`1<HarmonyLib.Public.Patching.HarmonyManipulator/PatchContext>,System.Collections.Generic.List`1<HarmonyLib.Public.Patching.HarmonyManipulator/PatchContext>,System.Collections.Generic.List`1<HarmonyLib.Public.Patching.HarmonyManipulator/PatchContext>,System.Collections.Generic.List`1<HarmonyLib.Public.Patching.HarmonyManipulator/PatchContext>,bool) <0x00ba6>
HarmonyLib.Public.Patching.HarmonyManipulator.Manipulate (System.Reflection.MethodBase,HarmonyLib.PatchInfo,MonoMod.Cil.ILContext) <0x00194>
HarmonyLib.Public.Patching.ManagedMethodPatcher.Manipulator (MonoMod.Cil.ILContext) <0x00069>
MonoMod.Cil.ILContext.Invoke (MonoMod.Cil.ILContext/Manipulator) <0x002f1>
MonoMod.RuntimeDetour.ILHook/Context.InvokeManipulator (Mono.Cecil.MethodDefinition,MonoMod.Cil.ILContext/Manipulator) <0x00076>
(wrapper dynamic-method) MonoMod.RuntimeDetour.ILHook/Context.DMD<MonoMod.RuntimeDetour.ILHook+Context..Refresh> (MonoMod.RuntimeDetour.ILHook/Context) <0x00452>
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<MonoMod.RuntimeDetour.ILHook+Context..Refresh>?303845760 (object) <0x0001c>
HarmonyLib.Internal.RuntimeFixes.StackTraceFixes.OnILChainRefresh (object) <0x0002e>
MonoMod.RuntimeDetour.ILHook.Apply () <0x0013a>
HarmonyLib.Public.Patching.ManagedMethodPatcher.DetourTo (System.Reflection.MethodBase) <0x001aa>
Rethrow as HarmonyException: IL Compile Error (unknown location)
HarmonyLib.Public.Patching.ManagedMethodPatcher.DetourTo (System.Reflection.MethodBase replacement)
HarmonyLib.PatchFunctions.UpdateWrapper (System.Reflection.MethodBase original, HarmonyLib.PatchInfo patchInfo)
Rethrow as HarmonyException: IL Compile Error (unknown location)
HarmonyLib.PatchFunctions.UpdateWrapper (System.Reflection.MethodBase original, HarmonyLib.PatchInfo patchInfo)
HarmonyLib.PatchProcessor.Patch ()
HarmonyLib.Harmony.Patch (System.Reflection.MethodBase original, HarmonyLib.HarmonyMethod prefix, HarmonyLib.HarmonyMethod postfix, HarmonyLib.HarmonyMethod transpiler, HarmonyLib.HarmonyMethod finalizer, HarmonyLib.HarmonyMethod ilmanipulator)
H3MP.Patches.InstantiationPatches.DoPatching (HarmonyLib.Harmony harmony)
H3MP.Patches.PatchController.DoPatching ()
H3MP.Mod.Init ()
H3MP.Mod.Start ()

[Info   : Unity Log] Updating Global Post Volumes:
[Info   : Unity Log] AO:False
[Info   : Unity Log] CC:True
[Info   : Unity Log] BL:False
[Info   : Unity Log] Scene delta is:0.01111111
[Info   : Unity Log] Oculus detected with 72 frequency
[Info   : Unity Log] Scene delta is:0.01111111
[Info   :      Deli] Loading [WurstMod 2.2.4] behaviours into runtime
[Info   :      Deli] Loading [MagazinePatcher 0.1.12] behaviours into runtime
[Info   :MagazinePatcher] MagazinePatcher runtime has started!
[Info   :MagazinePatcher] Patching has started
[Info   :MagazinePatcher] Otherloader detected!
[Info   :      Deli] Loading runtime assets from [MagazinePatcher 0.1.12]
[Info   : Unity Log] Setting for trackedDeviceIndex:2
[Info   : Unity Log] Setting control mode to CMODE:Oculus and DMODEQuest2 using modelname:oculus quest2 (right controller) and controllername:oculus_touch
[Info   : Unity Log] Setting for trackedDeviceIndex:1
[Info   : Unity Log] Setting control mode to CMODE:Oculus and DMODEQuest2 using modelname:oculus quest2 (left controller) and controllername:oculus_touch
[Info   : Unity Log] Prepping LIV Prefab
[Info   : Unity Log] LIV: Ready! Waiting for compositor.
[Info   : Unity Log] LIV Prefab Deployed
[Info   : Unity Log] Initializing - VersionRelease Update:109
[Warning:      Deli] Source URL of [BlackHawkDownTNH 1.0.0] is invalid
[Warning:      Deli] Source URL of [Hotel Hotlink 1.2.2] is invalid
[Info   :      Deli] [WurstMod 2.2.4] is up to date
[Info   :      Deli] [Deli 0.4.2] is up to date
[Message:      Deli] Runtime stage finished
[Info   : Unity Log] Prewarm Completed Lambda
[Info   : Unity Log] Prewarm Completed GUI Check
[Info   :OtherLoader] [1.348 s] Completed loading bundle (otherloader_assets)
[Info   :OtherLoader] [1.370 s] Completed loading bundle (any_altmags)
[Info   :OtherLoader] Registered asset bundle to load later (late_any_altmags)
[Message:   Stratum] Loading complete (15.295s)
[Info   :MagazinePatcher] Cache file found! Is Valid? True
[Info   :MagazinePatcher] Applying magazine cache to firearms
[Info   :OtherLoader] All Items Loaded! Total Load Time : 3.421 seconds
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
H3MP.WristMenuSection.OnHostClicked (UnityEngine.UI.Text textRef)
H3MP.WristMenuSection+<>c__DisplayClass13_0.<InitButton>b__0 ()
UnityEngine.Events.InvokableCall.Invoke (System.Object[] args)
UnityEngine.Events.InvokableCallList.Invoke (System.Object[] parameters)
UnityEngine.Events.UnityEventBase.Invoke (System.Object[] parameters)
UnityEngine.Events.UnityEvent.Invoke ()
FistVR.FVRPointableButton.OnPoint (FistVR.FVRViveHand hand)
FistVR.FVRViveHand.set_CurrentPointable (FistVR.FVRPointable value)
FistVR.FVRViveHand.Update ()

[Info   :      H3MP] Closing server.
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
H3MP.GameManager.TakeAllPhysicalControl (Boolean destroyTrackedScript)
H3MP.Networking.Server.Close ()
H3MP.Networking.ThreadManager.OnApplicationQuit ()

[Info   : Unity Log] LIV: Disabled, cleaning up.

**Comment by TommySoucy** [comment]
As I asked earlier, were you and your friends on "alpha - mod safe"?

If not, you're gonna have to switch to it.

**Comment by DMJester** [comment]
Steam - H3VR - Properties - Betas ..?
If you're talking about the Beta side, I was playing with it set to None.

**Comment by TommySoucy** [comment]
Yes, I was talking about the beta. It should work if you change it.

**Comment by DMJester** [comment]
As you said, there is no problem playing after switching to Alpha - Mode Safe

Thank you so much
