### ISSUE TITLE
Unable to see friend

### ISSUE THREAD

**Issue by gbeara98** [TommySoucy/H3MP#130]
We have tried both 1.6.7, and 1.6.5, with their respective compatible BepinEx versions, and are able to join eachother, but unable to see eachother, items can be picked up, but only seen when dropped. We are on the mod friendly version of the game as well.

**Comment by TommySoucy** [comment]
Send logs
Make sure you are on "alpha - mod safe"

**Comment by gbeara98** [comment]
We are on alpha mod safe
[LogOutput.log](https://github.com/TommySoucy/H3MP/files/12105706/LogOutput.log)

**Comment by TommySoucy** [comment]
The logs indicate 1.6.5, which is outdated. Try 1.6.7 again on alpha - mod safe and send the logs again

**Comment by gbeara98** [comment]
[LogOutput.log](https://github.com/TommySoucy/H3MP/files/12111443/LogOutput.log)
