### ISSUE TITLE
Softlock in Take and hold mode

### ISSUE THREAD

**Issue by Yuggeo** [TommySoucy/H3MP#182]
Thanks for the great mod, but when my friend and I start playing TNH, a strange thing happens. At first everything happens as usual, my friend in TNH mode joins me in the lobby, we start playing, we reach the objective, but when one of us clicks on the blue sphere “system node” the game gets stuck. A red barrier appears around us, but nothing happens, no enemies appear, no targets appear. We waited for about 5 minutes but nothing progressed. All opponents, items, objective locations are synchronized perfectly. Each of us has tried hosting, and we also do not use other mods.

**Comment by TommySoucy** [comment]
Is this on the newest update? H3MP is not up to date yet

**Comment by NeoKesha** [comment]
Yes, it also happens in single player is H3MP is active. Started to happen after newest update.
I use H3MP for Player Body mod

**Comment by TommySoucy** [comment]
Like I said, H3MP is not up to date yet. You'll have to remove it from your profile for now if you want to play TNH.
