### ISSUE TITLE
[SUGGESTION] Translucent Playerbody to make quick belt more visible

### ISSUE THREAD

**Issue by muskit** [TommySoucy/H3MP#219]
The playerbody is really cool to have, but it makes interacting with the quickbelt a lot more difficult due to the playerbody obstructing the quickbelt. I think one way to solve that is to allow the playerbody to become translucent. There's a couple approaches that can be taken for this:

- Make self-opacity an option in the wrist menu that can be adjusted on the fly
- Dynamically decrease self-opacity when looking down, perhaps to a player-configured target opacity

Both of these can even be added at the same time, where a wristmenu button toggles the dynamic opacity.

**Comment by TommySoucy** [comment]
Feel free to make a pull request
