### ISSUE TITLE
[BUG] Unable to join via direct connect

### ISSUE THREAD

**Issue by likeusb** [TommySoucy/H3MP#228]
Trying to directly join a friend's server, but it never receives the server welcome and times out.
Currently running the latest version of every mod I have. If it's of any use, here's (what I think is?) my profile code to easily get the mod list I'm running: 018f68ac-4504-da91-e25c-240948ae45d3
I'm running the Alpha branch on Steam

Attached a log file below from the latest session of failure, if it's of any help.
[LogOutput.log](https://github.com/TommySoucy/H3MP/files/15283676/LogOutput.log)

**Comment by TommySoucy** [comment]
Not a bug, your friend's server is just not set up properly. I also can't guarantee the mod works on alpha.

Plenty of people have the same problem, find help on the homebrew discord: https://discord.gg/83yTrfr
