### ISSUE TITLE
API to support networking of custom content

### ISSUE THREAD

**Issue by nrgill28** [TommySoucy/H3MP#47]
It would be great if there was some way for other mods to interact with H3MP to enable better networking of modded content, particularly custom gamemodes, extra map elements, and custom gun scripts.

At a minimum, I would like to have callbacks for important events like player joins / leaves, scene switching, etc. as well as being able to include the code required to serialize and deserialize custom classes from within my own mod.

I expect something like this to be low priority as it would be best to get H3MP to a stable and complete point before attempting to add an API for other mods to interact with it, to avoid needing to make major breaking changes to the API. Though with that said I would love to help with this in both code and planning for what the API would require.

**Comment by TommySoucy** [comment]
Having an event system other mods can subscribe to is planned, like you said though, low priority for now.

I'm not sure if it is at all possible but how I think it could be done now using Harmony would be adding H3MP as a BepinEx soft dependency to your mod so it is loaded first, then checking if H3MP is one of the loaded plugins. There are other ways but this would be the simplest way I can think of to make sure the H3MP assembly exists, at which point you could simply patch the relevant methods using Harmony.

The relevant methods being the ones labelled by "// MOD:" inside my code.

With this you should be able to do pretty much anything until I add in a better system.

**Comment by TommySoucy** [comment]
Done with release 1.6.0

Probably some stuff missing to support all possible mod cases but I'll add those as I keep working on it.

Check out these videos: https://www.youtube.com/playlist?list=PLihalOcCiwZCuiXGBfpHY48palyNLl9ef

I'll be building a bit of a github wiki for this when I have time.
