### ISSUE TITLE
When taking vault weapon hand it to the 2nd player the weapons attachments got detached

### ISSUE THREAD

**Issue by G894** [TommySoucy/H3MP#54]
Old item spawner in TNH, vanilla weapon and attachments. including meg, red dot.

**Comment by TommySoucy** [comment]
Should have been fixed on latest release, will review

**Comment by TommySoucy** [comment]
Could not replicate in latest version. Can you confirm this still happens? And can you replicate consistently?

**Comment by TommySoucy** [comment]
When this happens are you hosting or is your friend hosting?

**Comment by G894** [comment]
we tried both the first picture was he hosting the network, and the second picture was me hosting the network. 

the first picture, the attachments floating around the gun and they are "functional"
the second picture, the attachment exploded when he holds the gun.

**Comment by G894** [comment]
we tried newly saved gun and old save they are the same

**Comment by TommySoucy** [comment]
So this was probably fixed alongside the changes I made to attachment tracking system and supporting prebuilt stuff, I was never able to replicate.

And when you say "hand it to the 2nd player" do you mean literally taking it from their hand?

Anyway, let me know if this still happens on the latest release if you ever play again

**Comment by G894** [comment]
The attachment is fine, except the red dot projection of the red dot sight on my guns from my vault do not show when another player is using the gun. he can fix it by remove and reattach that red dot sight.

**Comment by TommySoucy** [comment]
Ill close this for now and reopen if it pops up again
