### ISSUE TITLE
No item spawner for 2nd player even the item spawner is enable in both play's TNH config. 

### ISSUE THREAD

**Issue by G894** [TommySoucy/H3MP#55]
also do you take donation？

**Comment by TommySoucy** [comment]
> also do you take donation？

https://ko-fi.com/tommysoucy

And ill review the issue, thanks

**Comment by TommySoucy** [comment]
Fixed with 1.5.1, item spawner will now be spawned by start equipment button

**Comment by G894** [comment]
Confirm
