### ISSUE TITLE
placed grabbing hook can not be seen by 2nd player. 

### ISSUE THREAD

**Issue by G894** [TommySoucy/H3MP#56]

**Comment by TommySoucy** [comment]
What is a grabbing hook?

**Comment by G894** [comment]
Sorry, should be Grappling Hook.
As in this Dev log
https://www.youtube.com/watch?v=YMZDSmqG5Rc

**Comment by TommySoucy** [comment]
Last time I tested them they worked, ill review

**Comment by TommySoucy** [comment]
Done for next release
