### ISSUE TITLE
(1.4.0) hosting IP binds to 0.0.0.0 regardless of IP set in config.

### ISSUE THREAD

**Issue by beatcrazed** [TommySoucy/H3MP#65]
I'm trying to host a game on version 1.4.0.  I have set my external IP in the config file but whenever I start the server it binds to 0.0.0.0
I can tell it's reading the config file because it gets the port correct, and because when I tell it to join the log spits out a connection attempt to the correct IP. 

I've also tried my local IP (didn't work, used 0.0.0.0) and some random other numbers (also didn't work, used 0.0.0.0)

Attached is the logfile from my last attempt in which I had only H3MP and BepinEX loaded to eliminate the possibility of other mods somehow messing with the process.

[logfile.txt](https://github.com/TommySoucy/H3MP/files/11036892/logfile.txt)

In the meantime I'll step back through the versions of h3mp one by one and see when the problem was introduced, or otherwise if it's unique to me somehow.

**Comment by beatcrazed** [comment]
Okay, so my dingus friend got the port wrong when he was trying to join me. It's still confusing that it says 0.0.0.0 when hosting since that makes it seem like something is wrong. Oh well.

Thanks for developing h3mp :D

**Comment by TommySoucy** [comment]
The host listens to the specified port, it doesn't need an IP to be specified at all.

This console output is clearer in next release.
