### ISSUE TITLE
Game Desync after some playtime non modded and modded characters

### ISSUE THREAD

**Issue by Knepnep** [TommySoucy/H3MP#72]
Hello me and my friend played the mod for the past week now and after a few minutes or hour we desync no matter what we play (TnH)
we tried modded characters and non modded and they both desync is there any fix too this (we using hamachi)

**Comment by FiddyDidds** [comment]
It only seems to happen on the third hold, just after the second hold is completed the connected player (none-host) desyncs from the host and the hold doesn't end, it stays in the state that stops you leaving the room the hold is in. Weapons, enemies and ammo desync too. It happened when Nep hosted and when I also did.

**Comment by buggybooz12** [comment]
My friend and I will probably be playing through h3 together, I'll see if we can reproduce this on our end if at all as we'll be using Hamachi for the connection most likely.

**Comment by TommySoucy** [comment]
Refer to #119 for any further TNH desync problems
