### ISSUE TITLE
Take and Hold - non-host teleporting and losing weapons when host activates a hold

### ISSUE THREAD

**Issue by theFroh** [TommySoucy/H3MP#77]
Hey, I've been playing this on and off with a buddy and while it's been amazing fun (thanks so much for working on this and even getting it to the point it is now!), one significant issue we've had is as follows:

(I am host, mate is the only other connected client, we're playing otherwise unmodded T&H)
1. I purchase a weapon from a vault, and hand off a weapon to the mate.
2. Sometimes the mate can never see a hold (no blue sphere), and if I hit the sphere on my end, they are teleported to what appears to be a previous hold position.
3. They lose the weapon(s) they've been given, and are locked in with the regular T&H red laser grids, unable to make their way to my position

Quite a strange one, with a lot of moving parts that could be to blame, I know! I mention the weapon exchange as I'm fairly certain this issue has only occurred after doing that, and I've tried fully setting the weapon down somewhere for them to pick up in an attempt to mitigate ownership problems, but no change there.

**Comment by TommySoucy** [comment]
Who was TNH instance host?
Who went in the game first if not at the same time?
For 1.: why hand it to them, could they not see the panel from the supply point or was it the item spawner?
Your game was clearly desynced by 2., since they got TPed to the wrong point, but TP is supposed to happen.
For 3.: Weapon being interacted with by another player outside the bounds of a hold point started by someone else being destroyed is fixed for the next release.

Please send your logs

**Comment by theFroh** [comment]
I was the host.
1. Simply because I had an extra weapon after purchasing the new one, and it was a better weapon than theirs.
2. Gotcha, so once we get to that point it's completely desync'd.
3. Nice!

Unsure how common it is but typically the panels are at least on different walls between us, but usually in the same room. Should they be identical and in the same places or is that an early sign of desync as well?

The next time we do a run I'll make sure to grab the logs.

**Comment by theFroh** [comment]
Gotcha. Here's what we typically do:
1. Both launch the game, both open the T&H scene from the main menu.
2. I use the wrist menu to host, and confirm on the panel that appears in the T&H lobby.
3. Mate joins my server and is now present in the lobby too.
4. We ensure we select the same character (pretty sure it's been Classic Loadout for every case)
5. I eat my lobby hotdog. They eat their lobby hotdog.

Should we be doing anything differently? Cheers.

**Comment by TommySoucy** [comment]
Oh I was just asking about step 5

The idea is that whoever loads into TNH first will initialize the game and have control of it.

But once the TNH instance host joins, control is exchanged and given to them, and there are a lot of moving pieces when that happens so it can break more easily.

If the TNH instance host goes in first and initializes the game then no control exchange has to happen so it usually works out better.

**Comment by TommySoucy** [comment]
Refer to #119 for any further TNH desync problems
